name: Deploy infrastructure

on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        description: "Deploy to DEV?"
        required: true
        default: "true"

env:
  PROJECT_NAME: venezia

defaults:
  run:
    working-directory: infrastructure

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_to_dev }} == 'true'
    steps:
      - uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}

      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.DEV_AZURE_SUBSCRIPTION }}
          resourceGroupName: dev-${{ env.PROJECT_NAME }}-rg
          template: ./infrastructure/template.json
          parameters: ./infrastructure/parameters.dev.json projectName=${{ env.PROJECT_NAME }} dbAdministratorLoginPassword=${{ env.DB_PASS }}
        env:
          DB_PASS: ${{ secrets.DEV_DBSA_PASSWORD }}
